### PR TITLE
Add optimization vignette to documentation

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR will add an optimization vignette to the documentation. Please note that this PR is still in draft form, because the vignette is still being written, so please don't merge it yet. When it's ready for merging, I'll request a review.

### CODE REVIEW

**Comment by DanWismer** [comment]
Thanks @jeffreyhanson !

Did you create the `add-opt-docs` branch off of dev? I am confused now why those previous commits of mine are showing up?

**Comment by jeffreyhanson** [comment]
Yeah, I thought I created the new branch off dev - I don't know why those extra commits are there. To avoid issues, maybe it would be easier if I a new PR off the dev branch and copy the changes into the new branch, when this ready for review?

**Comment by DanWismer** [comment]
Sounds good and worth a try. My mental model is: 

1. Make sure local dev and main branch is in sync with the remote (this may require a local git pull)
2. Create feature branch off of dev
3. Squash and merge feature branch into dev (via pull request). 
4. Merge commit dev into main (via pull request) 

I am hoping with this workflow, we shouldn't see any of those older commits.

**Comment by jeffreyhanson** [comment]
Ok sounds - yeah, that workflow seems like it should work.

**Comment by jeffreyhanson** [comment]
Since the dev branch has been updated a lot since this PR was originally created, I'll close this PR and create a new one.

**Pull request closed without merging**
