### PR TITLE
302 gurobi

### PR DESCRIPTION
**Pull request by DanWismer**
I have this working locally via golem run_dev.r and in the web-apps repo docker swarm / shiny proxy localhost:3939.

The gurobi switch is only visible when running where to work locally in dev mode and when launching from the web-apps shiny proxy container in staff-advanced and admin roles.

### CODE REVIEW

**Comment by edwardsmarc** [comment]
Great work @DanWismer! The PR looks good to me on paper. I'll test it locally on Monday.

I'm wondering what will happen if someone tries to run WTW locally when they don't have a gurobi license on their C drive. I guess they'll have to turn the gurobi checkbox off and it will revert to cbc. Otherwise they'll get probably get an error from prioritizr. I'll try and test this case next week.

**Comment by DanWismer** [comment]
How it works is that there is a new toggle switch beside the optimize button. When the switch is on and an optimization is ran, it will try `add_gurobi_solver()` in the `min_set_result` or `min_shortfall_result`. If there is any error with the license (in use, or not found) it will exit the try block with an error message. The user can then wait and try again, or untoggle the switch to use the CBC solver.

Everything is explicitly set by the user. I don't have it where it will atomically switch between Gurobi and CBC

**Comment by DanWismer** [comment]
@ricschuster @jeffreyhanson  @edwardsmarc 

I copied the gurobi.lic file to the server: /opt/license/gurobi.lic

**Comment by edwardsmarc** [comment]
@DanWismer this is working great for me. I tried moving my license file out of C: while running WTW locally and sure enough, as soon as the license moves I get the error that the license is in use.

Hopefully we won't have many people wanting to run this locally, but anyone that does will need to remember to install the R gurobi package manually.

**Comment by DanWismer** [comment]
awesome thanks @edwardsmarc ! I will squash and merge after lunch and see what happens. 

If users want to run locally, I figure they will either need their own license file, or would have to request the one we have. I am hoping we can slow down support on having people run WTW locally.  The thing that is holding that back is #295 and #316

**Pull request merged**
