### PR TITLE
issue 327 fix download when PUs are sf

### LINKED ISSUE #327: Spatial PU export fails
This [commit](https://github.com/NCC-CNC/wheretowork/pull/314/files#diff-2173808b2728bcb3ea9d4bbf0de385ec269bee96aec8808242043a82c16ed725) for #307 breaks the download button when PUs are in `sf` format.

The `terra::rast()` call needs to move inside the `write_spatial_data()` function because `write_spatial_data()` can take a `raster` or an `sf` object:

```
write_spatial_data <- function(x, dir, name) {
  assertthat::assert_that(
    inherits(x, c("sf", "SpatRaster")),
    assertthat::is.string(dir),
    assertthat::noNA(dir),
    assertthat::is.string(name),
    assertthat::noNA(name)
  )
  # save data to disk
  if (inherits(x, "sf")) {
    ## save vector data in ESRI Shapefile format
    sf::write_sf(x, file.path(dir, paste0(name, ".shp")))
  } else {
    ## save raster data in GeoTIFF format
    suppressWarnings({
      writeNamedRaster(
        x = terra::rast(x), filename = file.path(dir, paste0(name, ".tif")),
        overwrite = TRUE, NAflag = -9999
      )
    })
  }
```

### PR DESCRIPTION
**Pull request by edwardsmarc**
Moved `terra::rast()` call into `write_spatial_data()`.

Fixes error where download failed because `server_export_data.R` was attempting to convert the sf object to a `SpatRaster`.

The error in this case was not crashing the app, the download widget within the browser was throwing an error and not exporting the .zip.

closes #327

### CODE REVIEW

**Comment by edwardsmarc** [comment]
Yes, I need to get familiar with the tests. What's your general workflow? Update the code, run checks() and then fix any failing tests?

**Comment by DanWismer** [comment]
What I do is figure out what tests are failing, make some changes on the specific file(s), then run the code line by line. That way you don't have to run through all the tests with `devtools::test()`. Then once all the individual tests that failed are passing, I do a full `devtools::check(args = "--no-multiarch", build_args="--no-multiarch")`

---

The fail is here: https://github.com/NCC-CNC/wheretowork/blob/b6bef9ce096cdbfc2bb860dc8ab187b4de4676ae/R/utils_spatial_io.R#L76
`x` is still a `RasterLayer`.

For the short term we can change it to ` inherits(x, c("sf", "RasterLayer "))`. It would be nice to upgrade everything to terra (#315), but that will require more time/effort.

**Comment by edwardsmarc** [comment]
OK, I'll run through that workflow again.

**Comment by DanWismer** [comment]
nice work! I tested for both raster and shp projects and both are downloading. The checks all passed on my end as well:
image

This PR is good to squash and merg. Thanks @edwardsmarc!

**Review by DanWismer — APPROVED** [review]

**Pull request merged**
