### PR TITLE
update vignettes and package website

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR contains updates to the vignettes. The main changes are a new optimization vignette that provides information on the optimization process, and an update to the user manual that provides more detail on the spatial clustering process.

Could you please let me know what you think? Happy to revert or discuss any changes - just let me know?

In particular, here is a list of all changes and their rationale:

- Fixed various small typos in the vignettes.
- Standardized text wrapping in the vignettes. Previousy, text that should belong to the same paragraph was split across multiple lines. This can sometimes lead to undesireable behavior where sentences that should belong to the same paragrpah are split into multiple paragraphs. Now, all text that belongs to the same paragraph is on the same line. To help with viewing the text (e.g., so you don't need to scroll horizontally to view all the text for a paragraph), you may need to enable text wrapping on your editor.
- Standardized formatting when referring to the "Where to Work" tool in vignettes (i.e., all vignettes now italicize the tool name). 
- Moved the vignettes from `vignettes/article` to `vignettes`. This is because  it is standard practice for R packages to put vignettes directly in the `vignettes` folder.
- Renamed the `wtw_user_manual.Rmd` to `wheretowork.Rmd`. This was done so that the user manual is now displayed prominently in the navigation bar for the package website (under "Getting Started") - which will help make it easier for users to find.
- Renamed the "Articles" button on the navigation bar to "Advanced topics". The Advanced topics button does not include the user manual (since that it is now accessible under Getting Started). Since all of the vignettes (except for the user manual) start with a disclaimer saying that the user should read the user manual first, putting them under Advanced topics might better describe the audience for the remaining vignettes.
-  Added redirects so that anyone trying to access the user manual via the old URL (i.e., https://ncc-cnc.github.io/wheretowork/articles/wtw_manual.html) will automatically resolve to the new URL (i.e., https://ncc-cnc.github.io/wheretowork/articles/wheretowork.html).
- New vignette describing the optimization process (see `vignettes/wtw_optimization.Rmd`)
- Added more detail to spatial clustering process (see `vignettes/wheretowork.Rmd`)
- Added more detail for handling categorical and probability data (see `vignettes/wtw_data.Rmd`)

Note that the package website was rebuilt using pkgdown version 2.1.0, because there seems to be a bug in the latest version (i.e., version 2.1.1) that fails to correctly render images in the vignettes.

### CODE REVIEW

**Comment by DanWismer** [comment]
Thanks @jeffreyhanson !

One thing I noticed is the user manual is missing:
image

Could we add this back in as a drop down item?

**Comment by jeffreyhanson** [comment]
Thanks for looking into this!

Re user manual issue: Yeah, in the PR, the user manual is available under "Get started" rather than "Advanced topics". What do you think? Happy to put the user manual back under advanced topics, though perhaps then it would be better to just call it "Articles" instead of "Advanced topics" then?

Re navar issue: Ah, thanks for catching that!

**Comment by DanWismer** [comment]
> Thanks for looking into this!
> 
> Re user manual issue: Yeah, in the PR, the user manual is available under "Get started" rather than "Advanced topics". What do you think? The standard practice for pkgdown websites is to put the main package overview/introduction/ tutorial under Get Started. I'm happy to put the user manual back under Advanced Topics instead though, but perhaps then it would be better to just call it "Articles" instead of "Advanced topics" then?
> 
> Re navar issue: Ah, thanks for catching that!

Ah yes, sorry I missed that. Having the user manual in the "Get Started" makes sense to me. 

Really weird about the images not showing, I am getting that with `pkgdown 2.1.1`. When it builds the site from the .Rmd files and translates to html, the source path on the images get this weid **%2F**. If you change the path from %2F to /, it works. Odd thing is that I recreated this site on the WTW 1.0.0 version without this problem.

**Comment by DanWismer** [comment]
@jeffreyhanson could you give this a test?

I changed it so we don't link to articles via the web address, but rather to the internal .hml source path.
before:
`[official manual](https://ncc-cnc.github.io/wheretowork/articles/wtw_manual.html)`
now:
`[official manual](wheretowork.html)`

How did you get the NEWS to updated? I changed it to 1.0.1

**Comment by jeffreyhanson** [comment]
> Really weird about the images not showing, I am getting that with `pkgdown 2.1.1`. When it builds the site from the .Rmd files and translates to html, the source path on the images get this weid **%2F**. If you change the path from %2F to /, it works. Odd thing is that I recreated this site on the WTW 1.0.0 version without this problem (oh that's because I used 2.1.0).

Yeah, I get that too with pkgdown 2.1.1, I think think there's a bug with it. I'm building the package with version 2.1.0 to avoid this issue.

> I changed it so we don't link to articles via the web address, but rather to the internal .html source path. before: `[official manual](https://ncc-cnc.github.io/wheretowork/articles/wtw_manual.html)` now: `[official manual](wheretowork.html)`

Yeah, I think that works better.

> How did you get the NEWS to updated? I changed it to 1.0.1

Just by rebuilding the website. Did this not work on your computer? Maybe another with pkgdown version 2.1.1?

**Comment by jeffreyhanson** [comment]
Also, I see that the package is still version 1.0.0 in the DESCRIPTION. Since the NEWS has 1.0.1, I'll do a bump the version to 1.0.1?

**Comment by jeffreyhanson** [comment]
I've just done a version bump, edited the NEWS file to fix some tpyos and standardize formatting, and rebuilt the vignettes and package website. This fixes the navbar issue for me, and it's now showing version 1.0.1 in the website NEWS page.

**Comment by DanWismer** [comment]
Thanks Jeff, this looks good to me. I will push to the dev branch and then to main.

**Comment by jeffreyhanson** [comment]
Awesome - thanks!

**Pull request merged**
