### PR TITLE
Made `RandomFields` a soft dependency (moved to suggests).  fix #208.

### LINKED ISSUE #208: ERROR: dependency 'RandomFields' is not available for package 'wheretowork'
When installing wheretowork:

if (!require(remotes)) install.packages("remotes")
remotes::install_github("NCC-CNC/wheretowork")

I get an error saying: 
ERROR: dependency 'RandomFields' is not available for package 'wheretowork'

It looks like RandomFields has been removed from CRAN?
https://cran.r-project.org/web/packages/RandomFields/index.html

### PR DESCRIPTION
**Pull request by DanWismer**
Updated all tests that use `RandomFields` to skip if not installed. Updated all simulation functions to assert that `RandomFields` exists. 

Note: the `RandomFields` package was removed from CRAN. This has happened in the past and the package author may bring it back...

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
@DanWismer - awesome - yeah that's right!

**Comment by jeffreyhanson** [comment]
If you only want to rebuild the site web pages affected by the changes, loook at the `make quicksite` command.

**Comment by DanWismer** [comment]
@jeffreyhanson, any idea why a test would fail on the Ubuntu (all packages) workflow? I ran `devtools::check(args = "--no-multiarch", build_args="--no-multiarch")` on my local and got 0 errors.  

image

I forget if you mentioned in one of our sessions that sometimes the checks randomly fail with GitHub Actions?

**Comment by jeffreyhanson** [comment]
Not sure sorry - maybe log file for the GitHub Actions might have some answers?

**Comment by jeffreyhanson** [comment]
Awesome - thanks!

**Pull request merged**
