### PR TITLE
Changed to 'upload shapefile' , fix #199

### LINKED ISSUE #199: change upload shapefile label in app
The "spatial dataset" label in the select drop-down menu widget for choosing data should say "upload shapefile".

### PR DESCRIPTION
**Pull request by DanWismer**
Changed "spatial dataset" label from the select drop-down menu widget to "upload shapefile"

### CODE REVIEW

**Comment by DanWismer** [comment]
Unsure at this moment why it failed the checks. Looking into the `test_read_project.R` for starters. I wouldn't think changing the label would impact the choice value downstream. I was able to load the `sim_shapefile.shp` on my local:

 
image

**Comment by jeffreyhanson** [comment]
Hmm, looks like latest run of CI tests on the main branch is showing similar failures.

**Comment by jeffreyhanson** [comment]
I'll see if I can update the main branch to fix these issues.

**Comment by jeffreyhanson** [comment]
Also - thanks for this!

**Pull request merged**
