### PR TITLE
Issue211

### PR DESCRIPTION
**Pull request by DanWismer**
Project on the fly

### CODE REVIEW

**Comment by DanWismer** [comment]
@jeffreyhanson , I added a new sim_shapefile_albers.shp to the extdata for testing. When I do `devtools::check(args = "--no-multiarch", build_args="--no-multiarch")` I get a warning that _inst/extdata/shapefile/sim_shapefile_albers.dbf_ is an executable. I recall you had a trick to fix this warning?

**Comment by jeffreyhanson** [comment]
Yeah, the WTD app had issues with that, so maybe look there? IIRC you might need to edit the DESCRIPTION file and add a BinaryFiles file to the repo.

**Comment by DanWismer** [comment]
I found this: 
https://stackoverflow.com/questions/70713010/convincing-r-that-the-dbf-file-associated-with-a-shp-file-is-not-an-executable 
And it worked! 
devtools::check() locally now doesn't flag .dbf as a .exe. Lets see how it does on github actions...

**Comment by DanWismer** [comment]
@jeffreyhanson, I am wondering if you came across a test passing on **Check** but failing on **Test coverage**? For some reason, the ubuntu workflows fails on `covr::codecov()`. 
image

Is there a reason why we run the tests twice; once in **Check** and a second in **Test coverage** ? I see that the `Test coverage` command in `R-CMD-check-ubuntu.yaml` starts on line 90. Wondering if I need to modify something there? This started to fail once I introduced the new **Ontario pilot dataset Albers**

All jobs pass on the the Windows workflow, but I notice there is no **Test coverage** job.

**Pull request merged**
