### PR TITLE
fix #330, holes in raster display

### LINKED ISSUE #330: continuous raster display has "holes"
I mostly notice this when vector species habitat data has been prepped as continuous. The "edges" show a gradient where the "core" displays these "holes".

image

### PR DESCRIPTION
**Pull request by DanWismer**
In the Variable class, I also set 0 value pixels to NA for display on the render method. I like the look for continuous. So far I don't think this messes up anything, but this for sure needs some good checks before going into production.

### CODE REVIEW

**Comment by edwardsmarc** [comment]
Thanks @DanWismer.
I'll test this tomorrow and get back to you.

**Comment by DanWismer** [comment]
Thanks! I need to update the tests if we are thinking some of these changes are OK

**Comment by DanWismer** [comment]
I am using this project to test:
[WTW.zip](https://github.com/NCC-CNC/wheretowork/files/12021674/WTW.zip)

**Comment by edwardsmarc** [comment]
Hey @DanWismer, I'm reading through your commits. Two make sense to me and two I can't figure out.

Why did you you need to set the min_value as the second smallest value? And why did you need to force the decimals on the min value in when setting breaks?

**Comment by DanWismer** [comment]
min values for each variable is always 0. However for WTW, 0 may as well be `NA` (mostly confident with that statement lol). I wanted to index the second smallest number so that the range is representative of the data (excluding 0's).

I round the decimals on the breaks because on some of our NAT layers such as carbon, rivers and climate, the smallest second number is 0.0000234 (I made that up, but you get the point). That long decimal then shows up on the legend label which is a bad look.

**Comment by edwardsmarc** [comment]
> min values for each variable is always 0. However for WTW, 0 may as well be `NA` (mostly confident with that statement lol). I wanted to index the second smallest number so that the range is representative of the data (excluding 0's).
> 
> I round the decimals on the breaks because on some of our NAT layers such as carbon, rivers and climate, the smallest second number is 0.0000234 (I made that up, but you get the point). That long decimal then shows up on the legend label which is a bad look.

Awesome! That all makes sense. And since `d[d==0] <- NA` is only applied to the data for rendering, it's not changing the values passed to prioritizr correct? Those would still use the zero's in the dataset class?

**Comment by DanWismer** [comment]
`d[d==0] <- NA` is for display only. The optimization uses the attribute.csv.

@jeffreyhanson 
It would be interesting if we could remove 0's altogether, starting from dataprep to attribute generation. However I think this is a bigger topic

**Comment by DanWismer** [comment]
... my concern with this PR is yes it may make the display look nicer (in my opinion) because it only shows continuous values > 0. However, I could be slowing things down by getting the second smallest number and also re-setting values ...

**Comment by edwardsmarc** [comment]
@DanWismer - I reviewed this and it works really nicely. I can't find anything in the code base that will be negatively impacted by this since it seems the changes are isolated to the rendering environment and the legend.

I could go either way on displaying the zero's. I agree it looks nicer with NAs but I can see some value in (beginner) users seeing that all planning units have a value for each Theme, even if that value is a zero.

I'm happy to push ahead with this PR.

**Comment by jeffreyhanson** [comment]
Hi,

Just regarding the zeros, I'd personally keep display them so that way users can see exactly what values each of the planning units has for each of the theme/weights/includes/excludes. E.g., if a planning unit has a zero for a particular layer, then it wouldn't appear on the map, if a user is trying to understand why a planning unit was selected in a solution, it might be confusing if the planning unit disappears when they view certain layers?

I agree that having zeros in a color ramp for layers with a large discontinuity could be rendered better. E.g., if there's a layer with continuous values from 100 - 500 and some planning units also have a value of zero - then a color ramp between 0 -- 500 might not show the spatial distribution very well. So, maybe a better way to handle this could be to have the legend show zeros using a single discrete color (e.g., pink) and then show the non-zero values using a continuous ramp (e.g., from blue to yellow). This way the zeros don't obscure the main distribution/variaiton, but they are also shown on the map. This might be a bit (or a lot?) more complicated to implement though?

**Comment by DanWismer** [comment]
Thanks guys.

I will remove the 0 to NA from this PR. I would like to revisit this sometime later as I think we can make the display better for these continuous layers. It find its mainly for species layers. 

I remember @edwardsmarc bringing this up, but perhaps every WTW project needs to display a planning unit layer. That way we could have 0 as NA, while also toggling on a planning unit layer for cartographic purposes, and reasons you mention Jeff about understanding planning unit selection.

**Pull request merged**
