### PR TITLE
Minor typo, default goal value to 0.3 based on the docstring

### PR DESCRIPTION
**Pull request by XavierCLL**
While reading the docstring I found a minor typo in the default `goal` to 0.3 based on the docstring in the new_feature function

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
Thanks for catching this @XavierCLL! @DanWismer, when you get a chance could you please take a look? Also, the website might need rebuilding after merging this PR.

**Comment by DanWismer** [comment]
Thanks @XavierCLL for finding that. I see that the `limit_goal` default also needs to be changed to 0 to reflect the docstring. Would you mind making that change as well?  After that, I can squash and merge this PR into the main branch.

**Comment by XavierCLL** [comment]
> Thanks @XavierCLL for finding that. I see that the `limit_goal` default also needs to be changed to 0 to reflect the docstring. Would you mind making that change as well? After that, I can squash and merge this PR into the main branch.

Hi @DanWismer done!
Thanks

**Comment by DanWismer** [comment]
Thanks! Once the github actions complete, I can squash and merge. Changes will then be seen on the production server the following day (if I get to merging this before end of day)

**Comment by jeffreyhanson** [comment]
Awesome - thanks @DanWismer and @XavierCLL!

**Pull request merged**
