### PR TITLE
issue #307, replace RandomFields

### PR DESCRIPTION
**Pull request by DanWismer**

### CODE REVIEW

**Comment by edwardsmarc** [comment]
## Checks

@DanWismer my check passed with 1 WARNING about the raster package being built under a different version of R. I also got a few a NOTES:
```
> checking package dependencies ... NOTE
  Imports includes 47 non-default packages.
  Importing from so many packages makes the package vulnerable to any of
  them becoming unavailable.  Move as many as possible to Suggests and
  use conditionally.

> checking installed package size ... NOTE
    installed size is 29.5Mb
    sub-directories of 1Mb or more:
      app       6.5Mb
      extdata  16.9Mb
      help      4.1Mb

> checking dependencies in R code ... NOTE
  Namespaces in Imports field not imported from:
    'R.utils' 'cachem' 'future' 'ipc' 'markdown' 'pkgload' 'plyr' 'rcbc'
    'rgdal' 'withr'
    All declared Imports should be used.

> checking R code for possible problems ... [22s] NOTE
  simulate_themes: no visible global function definition for 'na.omit'
  simulate_weights : <anonymous>: no visible global function definition
    for 'na.omit'
  Undefined global functions or variables:
    na.omit
  Consider adding
    importFrom("stats", "na.omit")
  to your NAMESPACE file.
```

I'm not sure if we need to address that last one in this branch?

## terra
The terra update for downloading rasters appears to work. But the behavior when you select multiple rasters to download is odd. It only ever downloads a single tif called data.tif, and if you have multiple rasters selected it adds them as different bands in data.tif. Is this the standard behavior? It does the same thing with the current published version of the app. I was expecting to get a tif for each layer I selected in the download widget.

**Comment by DanWismer** [comment]
Thanks @edwardsmarc !

We can address the notes on a different PR. These notes have been the same for sometime now.

For the data download, I believe this is the same behavior as before (I will check `Sites` to confirm). Instead of exporting individual .tifs, it exports the stack of rasters as a single multiband tif. If you open it up in Arc Catalog, you can drag in the individual rasters:

image

And each download has the same name, `data.tif`

**Comment by jeffreyhanson** [comment]
Just a heads up, the warning `no visible global function definition for 'na.omit'` can be addressed by replacing `na.omit` with `stats::na.omit`.

**Comment by DanWismer** [comment]
> Just a heads up, the warning `no visible global function definition for 'na.omit'` can be addressed by replacing `na.omit` with `stats::na.omit`.

Thanks Jeff! I was able to work in your prioritizr code for simulating data.

**Comment by jeffreyhanson** [comment]
Ah - awesome!

**Comment by DanWismer** [comment]
Intersecting, on sites, when you download, it names the multi band rasters as Band1, Band2, Bande etc.
image

I assume terra handles this better and actually assigns the raster name to the band?

**Comment by jeffreyhanson** [comment]
Yeah, IIRC using `terra::writeRaster` will preserve the layer names (unlike `raster::writeRaster`).

**Comment by edwardsmarc** [comment]
> Thanks @edwardsmarc !
> 
> We can address the notes on a different PR. These notes have been the same for sometime now.
> 
> For the data download, I believe this is the same behavior as before (I will check `Sites` to confirm). Instead of exporting individual .tifs, it exports the stack of rasters as a single multiband tif. If you open it up in Arc Catalog, you can drag in the individual rasters:
> 
> image
> 
> And each download has the same name, `data.tif`

Thanks for explanation @DanWismer. This makes sense, and I'm getting the same result: the terra version keeps the layer names but the raster version does not.

**Pull request merged**
